/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JFrame;

/**
 *
 * @author prabhavi
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RequestedRepairs = new javax.swing.JButton();
        RequestedRepairs1 = new javax.swing.JButton();
        RequestedRepairs2 = new javax.swing.JButton();
        RequestedRepairs3 = new javax.swing.JButton();
        RequestedRepairs4 = new javax.swing.JButton();
        RequestedRepairs6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 63, 130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(20, 41, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/appbar.close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 50, 20));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/appbar.chevron.down.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 20));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 70, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/appbar.circle.growth.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reports");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 800, 40));

        jPanel3.setBackground(new java.awt.Color(20, 41, 77));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/appbar.arrow.left.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel4.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/rsz_4.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 490));

        RequestedRepairs.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs.setText("Requests Report");
        RequestedRepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairsActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 180, 40));

        RequestedRepairs1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs1.setText("Monthly Checking Reports");
        RequestedRepairs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairs1ActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 210, 40));

        RequestedRepairs2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs2.setText("Lost Items Report");
        RequestedRepairs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairs2ActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 163, 180, 40));

        RequestedRepairs3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs3.setText("Daily Cleaning Reports");
        RequestedRepairs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairs3ActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 180, 40));

        RequestedRepairs4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs4.setText("Damage Items Reports");
        RequestedRepairs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairs4ActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 40));

        RequestedRepairs6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        RequestedRepairs6.setText("Damage Items Reports");
        RequestedRepairs6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedRepairs6ActionPerformed(evt);
            }
        });
        jPanel1.add(RequestedRepairs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestedRepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairsActionPerformed
        RequestedRepairs R1= new RequestedRepairs();
        R1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RequestedRepairsActionPerformed

    private void RequestedRepairs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairs1ActionPerformed
        RequestedRepairs R1= new RequestedRepairs();
        R1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RequestedRepairs1ActionPerformed

    private void RequestedRepairs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestedRepairs2ActionPerformed

    private void RequestedRepairs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestedRepairs3ActionPerformed

    private void RequestedRepairs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestedRepairs4ActionPerformed

    private void RequestedRepairs6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedRepairs6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestedRepairs6ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       Maintenance m1= new Maintenance();
       m1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestedRepairs;
    private javax.swing.JButton RequestedRepairs1;
    private javax.swing.JButton RequestedRepairs2;
    private javax.swing.JButton RequestedRepairs3;
    private javax.swing.JButton RequestedRepairs4;
    private javax.swing.JButton RequestedRepairs6;
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
